package contacts;

import javax.persistence.*;
import java.util.List;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * TClass generated by hbm2java
 */
@Entity
@Table(name = "contact")
public class Contact implements java.io.Serializable {

    private Long contactId;
    private String name;
    private List<Phone> phoneNumber;

    public Contact() {
    }

    public Contact(String name) {
        this.name = name;
    }

    @Id
    @GeneratedValue(strategy=IDENTITY)
    @Column(name="contactId", unique=true, nullable=false)
    public Long getContactId() {
        return this.contactId;
    }

    public void setContactId(Long contactId) {
        this.contactId = contactId;
    }

    @Column(name="name", nullable=false, length=20)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @ManyToMany( fetch = FetchType.LAZY, cascade = CascadeType.ALL  )
    @JoinTable(
            name = "contact_primary_phone",
            joinColumns = {@JoinColumn(name = "contactId", nullable = false, updatable = true)},
            inverseJoinColumns = {@JoinColumn(name = "phoneId", nullable = false, updatable = true)}
    )
    public List<Phone> getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(List<Phone> phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

}